@startuml InsectActions
hide empty description
title Insect Gameplay State Machine

[*]-->PlaceInsect
PlaceInsect-->MoveInsect : moveTo
MoveInsect --> EatSpore : eat
EatSpore --> MoveInsect : updateScore

MoveInsect --> CutMycelium : cut
CutMycelium -> MoveInsect : updateScore

MoveInsect --> MoveInsect : moveTo

@enduml