@startuml Mushroom
hide empty description
title Mushroom state machine

[*]-->OnlyMushroomHead
OnlyMushroomHead-->MyceliumGrowing: placeMycelium
MyceliumGrowing-> SmallSpreadSpore : smallSpread
SmallSpreadSpore --> MyceliumGrowing: updateScore

MyceliumGrowing--> LargeSpreadSpore : largeSpread
LargeSpreadSpore-> MyceliumGrowing: updateScore


MyceliumGrowing->BodyGrowing : placeBody
BodyGrowing-> MyceliumGrowing: updateScore

@enduml