@startuml 13. Fungus spreading spores

title 13. Fungus spreading spores

actor "Skeleton" as Ac
participant "fb : FungusBody" as Fb
participant "t : Tile" as T
participant "s : Spore" as S

activate Ac
activate Fb
activate T

Ac -> Fb : sporeCloud()
opt sporeCharge != 0
loop 
Fb -> S ** : <<create>>
activate S
S --> Fb
Fb -> T : addEntity(s)
T-->Fb

end
end
Fb --> Ac


@enduml