@startuml 18. Multiple mycelium growing on Tekton

title 18. Multiple mycelium growing on Tekton

actor "Skeleton" as Ac
participant "f1 : Fungus" as F1
participant "f2 : Fungus" as F2
participant "tek: Tekton" as Tek
participant "m1 : Mycelium" as M1
participant "m2 : Mycelium" as M2
participant "t : Tile" as T

activate Ac
activate F1
activate F2
activate T
activate Tek

Ac -> F1 : growMycelium()

F1->Tek : growMycelium(t)
opt canGrowMycelium
Tek -> M1 ** : <<create>>
activate M1
M1 --> Tek
Tek -> T : addEntity(m1)
T-->Tek
end
Tek-->F1

F1 --> Ac

Ac -> F2 : growMycelium()

F2->Tek : growMycelium(t)
opt canGrowMycelium
Tek -> M2 ** : <<create>>
activate M2
M2 --> Tek
Tek -> T : addEntity(m2)
T-->Tek
end
Tek-->F2

F2 --> Ac


@enduml