@startuml Insect eating

title 6. Insect eats Freeze Spore

actor "Skeleton" as PP
participant "i : Insect" as I
participant "fs : FreezeSpore" as Sp
participant "t : Tile" as T

activate I
activate T
activate Sp

PP -> I : eat(fs)
I -> Sp : getEaten(i)
Sp -> I : setSpeed(-100)
I --> Sp
Sp -> I : addSpore(fs)
I --> Sp

Sp -> T : removeEntity(fs)
T --> Sp
Sp --> I

I --> PP


@enduml