@startuml 7. Insect eats Cut Spore

title 7. Insect eats Cut Spore

actor "Skeleton" as PP
participant "i : Insect" as I
participant "cs : CutSpore" as Sp
participant "t : Tile" as T

activate I
activate T
activate Sp

PP -> I : eat(cs)
I -> Sp : getEaten(i)
Sp -> I : setCut(false)
I --> Sp
Sp -> I : addSpore(cs)
I --> Sp

Sp -> T : removeEntity(cs)
T --> Sp
Sp --> I

I --> PP


@enduml