@startuml SQ_CannotGrowBodyOnTecton
title 16. CannotGrowBodyOnTecton

actor "Skeleton" as Pp
participant "InsectPlayer" as Ip
participant "t : targetTile" as Tt
participant "t : Tekton" as T
participant "fb : FungusBody" as Fb

activate Pp
activate Ip
activate T
activate Tt

Pp -> Ip : growBody(targetTile)
Ip -> Tt : growBody(targetTile)
opt parentTekton.fungusBody == null
    Tt -> Fb : <<create>>
    activate Fb
    Fb --> Tt
    Tt -> T : setBody(fungusBody)
    T --> Tt
end
Tt --> Ip
Ip --> Pp


@enduml