@startuml Fungus mushroom

title Fungus growing a mushroom

participant "fp : FungusPlayer" as Fp
participant "f : Fungus" as F
participant "t : Tile" as T
participant "fb : FungusBody" as Fb

activate Fp
activate F
activate T

Fp -> F : growBody(t)
F -> Fb ** : <<create>>
activate Fb
Fb --> F
F -> T : addEntity(fb)
F --> Fb


@enduml