@startuml Fungus mushroom

title 12. Fungus growing a mushroom

actor "Skeleton" as Ac
participant "fp : FungusPlayer" as Fp
participant "f : Fungus" as F
participant "t : Tile" as T
participant "fb : FungusBody" as Fb

activate Ac
activate Fp
activate F
activate T

Ac -> Fp : growBody(t)
opt actionPoints > 0
Fp -> F : growBody(t)
F -> Fb ** : <<create>>
activate Fb
Fb --> F
F -> T : addEntity(fb)
T --> F
F --> Fp
end
Fp --> Ac


@enduml