@startuml Fungus spores

title Fungus spreading spores

actor "Player person" as Ac
participant "fb : FungusBody" as Fb
participant "t : Tile" as T
participant "s : Spore" as S

activate Ac
activate Fb
activate T

Ac -> Fb : sporeCloud()
opt sporeCharge == 0
loop 
Fb -> S ** : <<create>>
activate S
S --> Fb
Fb -> T : addEntity(s)
T-->Fb

end
end
Fb --> Ac


@enduml