@startuml Insect thread cutting

title Insect cutting a thread


participant "i : Insect" as I
participant "m : Mycelium" as T
participant "t1 : Tile" as Tl1
participant "t2 : Tile" as Tl2
participant "connected : Mycelium" as Mc
participant "disconnected : Mycelium" as Md


activate I
activate T
activate Tl

opt canCut
I -> T : detach()
T->Mc : <<create>>

activate Mc

Mc-->T
T->Tl1 : addEntity(connected)
Tl1 --> T
T->Md : <<create>>

activate Md

Md-->T
T->Tl2 : addEntity(disconnected)
Tl2-->T

T->Tl1 : removeEntity(m)
Tl1-->T

T->Tl2 : removeEntity(m)
Tl2-->T

T --> I
destroy T

end


@enduml