@startuml Insect moving

title 1. Insect player moving to a tile

actor "Skeleton" as PP
participant " ip : InsectPlayer" as IP
participant "i : Insect" as I
participant "currentTile : Tile" as Tx
participant "targetTile : Tile" as Ty

activate PP
activate I
activate Tx
activate Ty
activate IP

'tell don't ask... 
PP -> IP : moveTo(targetTile)
opt actionPoints > 0
IP -> I : step(targetTile)
opt isValidStep(targetTile)
I -> Tx : removeEntity(i)
Tx --> I
I -> Ty : addEntity(i)
Ty --> I
end
I --> IP 
end

IP --> PP


@enduml